name: Validate CDA xml with saxon

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: setup JVM
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.2'
    
    - name: download Saxon-HE
      run: wget -q https://downloads.sourceforge.net/project/saxon/Saxon-HE/10/Java/SaxonHE10-3J.zip
      
    - name: extract Saxon-HE
      run: 7z e SaxonHE10-3J.zip
      
    - name: run saxon to transform schematron file
      run: java -jar saxon-he-10.3.jar -s:test.sch -xsl:processing_files/pipeline-for-svrl.xsl -o:validation.xsl

    - name: run saxon to validate the sample CDA xml file
      run: java -jar saxon-he-10.3.jar -o:whereDidIScrewUp.xml -s:Diagnostic_Imaging_Report.xml -xsl:validation.xsl
      
    - name: read validation results file
      run: cat whereDidIScrewUp.xml
