name: Validate CDA xml with saxon

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup JVM
      uses: actions/setup-java@v1
      with:
        java-version: '13.0.2'
    
    - name: Download Saxon-HE
      run: wget -q https://downloads.sourceforge.net/project/saxon/Saxon-HE/10/Java/SaxonHE10-3J.zip
